package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.15 09:52:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriatTest {



  // Generated by ComTest BEGIN
  /** testLisaa75 */
  @Test
  public void testLisaa75() {    // Kategoriat: 75
    Kategoriat kgt = new Kategoriat(); 
    Kategoria k1 = new Kategoria("ty�"); 
    Kategoria k2 = new Kategoria("opiskelu"); 
    Kategoria k3 = new Kategoria("muu"); 
    assertEquals("From: Kategoriat line: 80", 0, kgt.getLkm()); 
    kgt.lisaa(k1); 
    assertEquals("From: Kategoriat line: 82", 1, kgt.getLkm()); 
    kgt.lisaa(k2); 
    assertEquals("From: Kategoriat line: 84", 2, kgt.getLkm()); 
    kgt.lisaa(k3); 
    assertEquals("From: Kategoriat line: 86", 3, kgt.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista106 */
  @Test
  public void testPoista106() {    // Kategoriat: 106
    Kategoriat kat = new Kategoriat(); 
    Kategoria k1 = new Kategoria("opiskelu"); 
    k1.rekisteroi(); 
    int n = k1.getTunnusNro(); 
    Kategoria k2 = new Kategoria("työ"); k2.rekisteroi(); 
    assertEquals("From: Kategoriat line: 112", 0, kat.getLkm()); 
    try {
    kat.anna(0); 
    fail("Kategoriat: 113 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kat.lisaa(k1); 
    assertEquals("From: Kategoriat line: 115", "opiskelu", kat.anna(0).getNimi()); 
    assertEquals("From: Kategoriat line: 116", 1, kat.getLkm()); 
    kat.lisaa(k2); 
    assertEquals("From: Kategoriat line: 118", "työ", kat.anna(1).getNimi()); 
    assertEquals("From: Kategoriat line: 119", 2, kat.getLkm()); 
    kat.poista(n); 
    assertEquals("From: Kategoriat line: 121", 1, kat.getLkm()); 
    kat.poista(n+1); 
    assertEquals("From: Kategoriat line: 123", 0, kat.getLkm()); 
    try {
    kat.anna(0); 
    fail("Kategoriat: 124 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna143 */
  @Test
  public void testAnna143() {    // Kategoriat: 143
    Kategoriat kgt = new Kategoriat(); 
    Kategoria kg1 = new Kategoria("ty�"); 
    kg1.rekisteroi(); 
    Kategoria kg2 = new Kategoria("muu"); 
    kg2.rekisteroi(); 
    Kategoria kg3 = new Kategoria("opiskelu"); 
    kg3.rekisteroi(); 
    kgt.lisaa(kg1); 
    kgt.lisaa(kg2); 
    kgt.lisaa(kg3); 
    assertEquals("From: Kategoriat line: 159", "ty�", kgt.anna(0).getNimi()); 
    assertEquals("From: Kategoriat line: 160", "muu", kgt.anna(1).getNimi()); 
    assertEquals("From: Kategoriat line: 161", "opiskelu", kgt.anna(2).getNimi()); 
  } // Generated by ComTest END
}