package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.23 19:54:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriatTest {



  // Generated by ComTest BEGIN
  /** testAnna79 */
  @Test
  public void testAnna79() {    // Kategoriat: 79
    Kategoriat kgt = new Kategoriat(); 
    Kategoria kg1 = new Kategoria(); 
    kg1.rekisteroi(); 
    kg1.taytaSomeenTiedoilla(); 
    Kategoria kg2 = new Kategoria(); 
    kg2.rekisteroi(); 
    kg2.taytaSomeenTiedoilla(); 
    Kategoria kg3 = new Kategoria(); 
    kg3.rekisteroi(); 
    kg2.taytaSomeenTiedoilla(); 
    kgt.lisaa(kg1); 
    kgt.lisaa(kg2); 
    kgt.lisaa(kg3); 
    assertEquals("From: Kategoriat line: 98", 1, kgt.anna(0).getTunnusNro()); 
    assertEquals("From: Kategoriat line: 99", 2, kgt.anna(1).getTunnusNro()); 
    assertEquals("From: Kategoriat line: 100", 3, kgt.anna(2).getTunnusNro()); 
  } // Generated by ComTest END
}