package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.01 14:03:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriaTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi98 */
  @Test
  public void testRekisteroi98() {    // Kategoria: 98
    Kategoria k1 = new Kategoria("opiskelu"); 
    k1.rekisteroi(); 
    Kategoria k2 = new Kategoria("työ"); 
    k2.rekisteroi(); 
    Kategoria k3 = new Kategoria("pankkijutut"); 
    k3.rekisteroi(); 
    assertEquals("From: Kategoria line: 106", 1, k1.getTunnusNro()); 
    assertEquals("From: Kategoria line: 107", 2, k2.getTunnusNro()); 
    assertEquals("From: Kategoria line: 108", 3, k3.getTunnusNro()); 
  } // Generated by ComTest END
}