package passreg.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.06 11:01:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriatTest {



  // Generated by ComTest BEGIN
  /** testLisaa65 */
  @Test
  public void testLisaa65() {    // Kategoriat: 65
    Kategoriat kgt = new Kategoriat(); 
    Kategoria k1 = new Kategoria("tyo"); 
    Kategoria k2 = new Kategoria("opiskelu"); 
    Kategoria k3 = new Kategoria("muu"); 
    assertEquals("From: Kategoriat line: 70", 0, kgt.getLkm()); 
    kgt.lisaa(k1); 
    assertEquals("From: Kategoriat line: 72", 1, kgt.getLkm()); 
    kgt.lisaa(k2); 
    assertEquals("From: Kategoriat line: 74", 2, kgt.getLkm()); 
    kgt.lisaa(k3); 
    assertEquals("From: Kategoriat line: 76", 3, kgt.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista97 */
  @Test
  public void testPoista97() {    // Kategoriat: 97
    Kategoriat kat = new Kategoriat(); 
    Kategoria k1 = new Kategoria("opiskelu"); 
    k1.rekisteroi(); 
    int n = k1.getTunnusNro(); 
    Kategoria k2 = new Kategoria("tyo"); k2.rekisteroi(); 
    assertEquals("From: Kategoriat line: 103", 0, kat.getLkm()); 
    try {
    kat.anna(0); 
    fail("Kategoriat: 104 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kat.lisaa(k1); 
    assertEquals("From: Kategoriat line: 106", "opiskelu", kat.anna(0).getNimi()); 
    assertEquals("From: Kategoriat line: 107", 1, kat.getLkm()); 
    kat.lisaa(k2); 
    assertEquals("From: Kategoriat line: 109", "tyo", kat.anna(1).getNimi()); 
    assertEquals("From: Kategoriat line: 110", 2, kat.getLkm()); 
    kat.poista(n); 
    assertEquals("From: Kategoriat line: 112", 1, kat.getLkm()); 
    kat.poista(n+1); 
    assertEquals("From: Kategoriat line: 114", 0, kat.getLkm()); 
    try {
    kat.anna(0); 
    fail("Kategoriat: 115 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna135 */
  @Test
  public void testAnna135() {    // Kategoriat: 135
    Kategoriat kgt = new Kategoriat(); 
    Kategoria kg1 = new Kategoria("tyo"); 
    kg1.rekisteroi(); 
    Kategoria kg2 = new Kategoria("muu"); 
    kg2.rekisteroi(); 
    Kategoria kg3 = new Kategoria("opiskelu"); 
    kg3.rekisteroi(); 
    kgt.lisaa(kg1); 
    kgt.lisaa(kg2); 
    kgt.lisaa(kg3); 
    assertEquals("From: Kategoriat line: 146", "tyo", kgt.anna(0).getNimi()); 
    assertEquals("From: Kategoriat line: 147", "muu", kgt.anna(1).getNimi()); 
    assertEquals("From: Kategoriat line: 148", "opiskelu", kgt.anna(2).getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta163 */
  @Test
  public void testLueTiedostosta163() {    // Kategoriat: 163
    Kategoriat kat = new Kategoriat(); 
    Kategoria k1 = new Kategoria("opiskelu"), k2 = new Kategoria("tyo"); 
    k1.rekisteroi(); k2.rekisteroi(); 
    String hakemisto = "testi"; 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    kat.lisaa(k1); 
    kat.lisaa(k2); 
    kat.tallenna(hakemisto); 
    kat.lueTiedostosta(hakemisto);  // johon ladataan tiedot tiedostosta.
    Iterator<Kategoria> i = kat.iterator(); 
    Kategoria kTest = i.next(); 
    assertEquals("From: Kategoriat line: 179", "opiskelu", kTest.getNimi()); 
    Kategoria kTest2 = i.next(); 
    assertEquals("From: Kategoriat line: 181", "tyo", kTest2.getNimi()); 
    kat.tallenna(hakemisto); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator220 */
  @Test
  public void testIterator220() {    // Kategoriat: 220
    Kategoriat kgt = new Kategoriat(); 
    Kategoria kg1 = new Kategoria("tyo"); 
    Kategoria kg2 = new Kategoria("muu"); 
    Kategoria kg3 = new Kategoria("opiskelu"); 
    Iterator<Kategoria> iter = kgt.iterator(); 
    assertEquals("From: Kategoriat line: 226", false, iter.hasNext()); 
    try {
    iter.next(); 
    fail("Kategoriat: 227 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    kgt.lisaa(kg1); 
    assertEquals("From: Kategoriat line: 229", true, iter.hasNext()); 
    Kategoria k = iter.next(); 
    assertEquals("From: Kategoriat line: 231", kg1, k); 
    kgt.lisaa(kg2); 
    kgt.lisaa(kg3); 
    assertEquals("From: Kategoriat line: 234", kg2, iter.next()); 
    assertEquals("From: Kategoriat line: 235", kg3, iter.next()); 
    iter = kgt.iterator(); 
    assertEquals("From: Kategoriat line: 237", false, iter.next() == iter.next()); 
    assertEquals("From: Kategoriat line: 238", "opiskelu", iter.next().getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKorvaaTaiLisaa260 */
  @Test
  public void testKorvaaTaiLisaa260() {    // Kategoriat: 260
    Kategoriat kat = new Kategoriat(); 
    Kategoria k1 = new Kategoria("tyo"); 
    Kategoria k2 = new Kategoria("opiskelu"); 
    assertEquals("From: Kategoriat line: 264", false, kat.onMuutettu()); 
    kat.lisaa(k1); 
    kat.lisaa(k2); 
    kat.setMuutettu(false); 
    assertEquals("From: Kategoriat line: 268", "tyo", kat.anna(0).getNimi()); 
    k1.parse("1|viihde"); 
    kat.korvaaTaiLisaa(k1); 
    assertEquals("From: Kategoriat line: 271", "viihde", kat.anna(0).getNimi()); 
    assertEquals("From: Kategoriat line: 272", true, kat.onMuutettu()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKategoriat290 */
  @Test
  public void testAnnaKategoriat290() {    // Kategoriat: 290
    Kategoriat kat = new Kategoriat(); 
    Kategoria k1 = new Kategoria("tyo"); 
    Kategoria k2 = new Kategoria("opiskelu"); 
    kat.lisaa(k1); kat.lisaa(k2); 
    List<Kategoria> katet = kat.annaKategoriat(); 
    Iterator<Kategoria> i = katet.iterator(); 
    assertEquals("From: Kategoriat line: 298", k2, i.next()); 
    assertEquals("From: Kategoriat line: 299", true, i.hasNext()); 
    assertEquals("From: Kategoriat line: 300", k1, i.next()); 
    assertEquals("From: Kategoriat line: 301", false, i.hasNext()); 
  } // Generated by ComTest END
}