package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.31 11:19:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KategoriaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi107 */
  @Test
  public void testRekisteroi107() {    // Kategoria: 107
    Kategoria k1 = new Kategoria("opiskelu"); 
    k1.rekisteroi(); 
    Kategoria k2 = new Kategoria("työ"); 
    k2.rekisteroi(); 
    Kategoria k3 = new Kategoria("pankkijutut"); 
    k3.rekisteroi(); 
    int n1 = k1.getTunnusNro(); 
    int n2 = k2.getTunnusNro(); 
    int n3 = k3.getTunnusNro(); 
    assertEquals("From: Kategoria line: 117", true, n3 > n2); 
    n2 = n1 +1 ; 
    assertEquals("From: Kategoria line: 119", true, n1 < n2 && n2 < n3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString131 */
  @Test
  public void testToString131() {    // Kategoria: 131
    Kategoria k = new Kategoria(); 
    k.parse(" 1  | opiskelu"); 
    assertEquals("From: Kategoria line: 134", "1|opiskelu", k.toString()); 
    assertEquals("From: Kategoria line: 135", 1, k.getTunnusNro()); 
    assertEquals("From: Kategoria line: 136", "opiskelu", k.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse157 */
  @Test
  public void testParse157() {    // Kategoria: 157
    Kategoria k = new Kategoria(); 
    k.parse("1    | opiskelu"); 
    assertEquals("From: Kategoria line: 160", 1, k.getTunnusNro()); 
    assertEquals("From: Kategoria line: 161", "opiskelu", k.getNimi()); 
    assertEquals("From: Kategoria line: 162", "1|opiskelu", k.toString());
    k.rekisteroi(); 
    int n = k.getTunnusNro(); 
    k.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    k.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kategoria line: 167", n+20+1, k.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta210 */
  @Test
  public void testAseta210() {    // Kategoria: 210
    Kategoria k = new Kategoria("opiskelu"); 
    assertEquals("From: Kategoria line: 212", "opiskelu", k.anna(1)); 
    assertEquals("From: Kategoria line: 213", null, k.aseta(1, "  tyo")); 
    assertEquals("From: Kategoria line: 214", "tyo", k.anna(1)); 
    assertEquals("From: Kategoria line: 215", "" + k.getTunnusNro(), k.anna(0)); 
    assertEquals("From: Kategoria line: 216", null, k.aseta(2, "jotain")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna233 */
  @Test
  public void testAnna233() {    // Kategoria: 233
    Kategoria k = new Kategoria(); 
    k.parse("10|  sahkopostit"); 
    assertEquals("From: Kategoria line: 236", "10", k.anna(0)); 
    assertEquals("From: Kategoria line: 237", 10, k.getTunnusNro()); 
    k.aseta(1, "tyo"); 
    assertEquals("From: Kategoria line: 239", "tyo", k.anna(1)); 
    assertEquals("From: Kategoria line: 240", "tyo", k.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone258 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone258() throws CloneNotSupportedException {    // Kategoria: 258
    Kategoria alkuK = new Kategoria("tyo"); 
    Kategoria kopio = alkuK.clone(); 
    assertEquals("From: Kategoria line: 262", "tyo", kopio.anna(1)); 
    assertEquals("From: Kategoria line: 263", "tyo", alkuK.anna(1)); 
    assertEquals("From: Kategoria line: 264", null, kopio.aseta(1, "opiskelu")); 
    assertEquals("From: Kategoria line: 265", "tyo", alkuK.anna(1)); 
    assertEquals("From: Kategoria line: 266", "opiskelu", kopio.anna(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKysymys292 */
  @Test
  public void testGetKysymys292() {    // Kategoria: 292
    Kategoria k = new Kategoria(); 
    assertEquals("From: Kategoria line: 294", "Nimi", k.getKysymys(1)); 
    assertEquals("From: Kategoria line: 295", null, k.getKysymys(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo307 */
  @Test
  public void testCompareTo307() {    // Kategoria: 307
    Kategoria k1 = new Kategoria("tyo"); 
    Kategoria k2 = new Kategoria("opiskelu"); 
    Kategoria k3 = new Kategoria("Tyo"); 
    int n1 = k1.compareTo(k2); 
    int n2 = k2.compareTo(k1); 
    int n3 = k1.compareTo(k3); 
    int n4 = k3.compareTo(k2); 
    assertEquals("From: Kategoria line: 315", true, n1 > 0); 
    assertEquals("From: Kategoria line: 316", true, n2 < 0); 
    assertEquals("From: Kategoria line: 317", 0, n3); 
    assertEquals("From: Kategoria line: 318", true, n4 > 0); 
  } // Generated by ComTest END
}