package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.18 10:42:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaasyTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi124 */
  @Test
  public void testRekisteroi124() {    // Paasy: 124
    Paasy gmail1 = new Paasy(); 
    Paasy gmail2 = new Paasy(); 
    assertEquals("From: Paasy line: 127", 0, gmail1.getTunnusNro()); 
    gmail1.rekisteroi(); 
    int n1 = gmail1.getTunnusNro(); 
    assertEquals("From: Paasy line: 130", 0, gmail2.getTunnusNro()); 
    gmail2.rekisteroi(); 
    int n2 = gmail2.getTunnusNro(); 
    assertEquals("From: Paasy line: 133", true, n2 == n1 + 1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString179 */
  @Test
  public void testToString179() {    // Paasy: 179
    Paasy p = new Paasy(); 
    p.parse(" 1  | 4|  soturi123 | ankka@yahoo.com"); 
    assertEquals("From: Paasy line: 182", true, p.toString().startsWith("1|4|soturi123|ankka@yahoo.com")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse206 */
  @Test
  public void testParse206() {    // Paasy: 206
    Paasy p = new Paasy(); 
    p.parse("   3  |1 |  ankkaTHELion "); 
    assertEquals("From: Paasy line: 209", 3, p.getTunnusNro()); 
    assertEquals("From: Paasy line: 210", 1, p.getKategoriaId()); 
    assertEquals("From: Paasy line: 211", true, p.toString().startsWith("3|1|ankkaTHELion|"));  // on enemm‰kin kuin 3 kentt‰‰, siksi loppu |
    p.rekisteroi(); 
    int n = p.getTunnusNro(); 
    p.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    p.rekisteroi();  // ja tarkistetaan ett‰ seuraavalla kertaa tulee yht‰ isompi
    assertEquals("From: Paasy line: 217", n+20+1, p.getTunnusNro()); 
  } // Generated by ComTest END
}