package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.12 21:38:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaasytTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnna120 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testAnna120() throws IndexOutOfBoundsException {    // Paasyt: 120
    Paasyt pst = new Paasyt(); 
    assertEquals("From: Paasyt line: 123", 0, pst.getLkm()); 
    Paasy gmail1 = new Paasy(); 
    gmail1.rekisteroi(); 
    gmail1.taytaGmailTiedoilla(); 
    pst.lisaa(gmail1); 
    assertEquals("From: Paasyt line: 128", 1, pst.getLkm()); 
    Paasy gmail2 = new Paasy(); 
    gmail2.rekisteroi(); 
    gmail2.taytaGmailTiedoilla(); 
    pst.lisaa(gmail2); 
    assertEquals("From: Paasyt line: 133", 2, pst.getLkm()); 
    try {
    pst.anna(2); 
    fail("Paasyt: 134 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista167 */
  @Test
  public void testPoista167() {    // Paasyt: 167
    Paasyt pst = new Paasyt(); 
    Paasy p1 = new Paasy(); 
    p1.taytaGmailTiedoilla(); 
    p1.rekisteroi(); 
    Paasy p2 = new Paasy(); 
    p2.taytaGmailTiedoilla(); 
    p2.rekisteroi(); 
    assertEquals("From: Paasyt line: 175", 0, pst.getLkm()); 
    pst.lisaa(p1); 
    pst.lisaa(p2); 
    assertEquals("From: Paasyt line: 178", 2, pst.getLkm()); 
    pst.poista(p1.getTunnusNro()); 
    assertEquals("From: Paasyt line: 180", 1, pst.getLkm()); 
    pst.poista(p2.getTunnusNro()); 
    assertEquals("From: Paasyt line: 182", 0, pst.getLkm()); 
    try {
    pst.anna(0); 
    fail("Paasyt: 183 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    pst.anna(1); 
    fail("Paasyt: 184 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}