package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.27 10:37:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaasyTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi124 */
  @Test
  public void testRekisteroi124() {    // Paasy: 124
    Paasy gmail1 = new Paasy(); 
    Paasy gmail2 = new Paasy(); 
    assertEquals("From: Paasy line: 127", 0, gmail1.getTunnusNro()); 
    gmail1.rekisteroi(); 
    int n1 = gmail1.getTunnusNro(); 
    assertEquals("From: Paasy line: 130", 0, gmail2.getTunnusNro()); 
    gmail2.rekisteroi(); 
    int n2 = gmail2.getTunnusNro(); 
    assertEquals("From: Paasy line: 133", true, n2 == n1 + 1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString180 */
  @Test
  public void testToString180() {    // Paasy: 180
    Paasy p = new Paasy(); 
    p.parse(" 1  | 4|  soturi123 | ankkaAku"); 
    assertEquals("From: Paasy line: 183", true, p.toString().startsWith("1|4|soturi123|ankkaAku")); 
    p.parse("   2"); 
    assertEquals("From: Paasy line: 185", 2, p.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse208 */
  @Test
  public void testParse208() {    // Paasy: 208
    Paasy p = new Paasy(); 
    p.parse("   3  |1 |  ankkaTHELion "); 
    assertEquals("From: Paasy line: 211", 3, p.getTunnusNro()); 
    assertEquals("From: Paasy line: 212", 1, p.getKategoriaId()); 
    assertEquals("From: Paasy line: 213", true, p.toString().startsWith("3|1|ankkaTHELion|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    p.rekisteroi(); 
    int n = p.getTunnusNro(); 
    p.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    p.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Paasy line: 218", n+20+1, p.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone257 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone257() throws CloneNotSupportedException {    // Paasy: 257
    Paasy p = new Paasy(); 
    p.parse("   3  | 2|  Ankka Aku   | 123"); 
    Paasy kopio = p.clone(); 
    assertEquals("From: Paasy line: 262", p.toString(), kopio.toString()); 
    p.parse("   4  | 2|  toinen gmail   | 123sKfe"); 
    assertEquals("From: Paasy line: 264", false, kopio.toString().equals(p.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna285 */
  @Test
  public void testAnna285() {    // Paasy: 285
    Paasy p = new Paasy(); 
    p.parse("1|  2|  gmail| | ankkaaku@gmail.com"); 
    assertEquals("From: Paasy line: 288", "gmail", p.anna(1)); 
    assertEquals("From: Paasy line: 289", "", p.anna(2)); 
    assertEquals("From: Paasy line: 290", "ankkaaku@gmail.com", p.anna(3)); 
    p.parse("|||||kkkl123"); 
    assertEquals("From: Paasy line: 292", "", p.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta316 */
  @Test
  public void testAseta316() {    // Paasy: 316
    Paasy p = new Paasy(); 
    p.parse("1|  2|  gmail| | ankkaaku@gmail.com"); 
    assertEquals("From: Paasy line: 319", "gmail", p.anna(1)); 
    assertEquals("From: Paasy line: 320", "", p.anna(2)); 
    p.aseta(1, "toinen gmail"); 
    assertEquals("From: Paasy line: 322", "toinen gmail", p.anna(1)); 
    assertEquals("From: Paasy line: 323", "väärä sähköpostiosoite", p.aseta(3, "x@yahoo.com")); 
    assertEquals("From: Paasy line: 324", "ankkaaku@gmail.com", p.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals396 */
  @Test
  public void testEquals396() {    // Paasy: 396
    Paasy p1 = new Paasy(); 
    p1.parse("   3 | 1 | gmail   | soturi123"); 
    Paasy p2 = new Paasy(); 
    p2.parse("   3 | 1 | gmail   | soturi123"); 
    Paasy p3 = new Paasy(); 
    p3.parse("   3 | 1 | gmail   | soturi124"); 
    assertEquals("From: Paasy line: 404", true, p1.equals(p2)); 
    assertEquals("From: Paasy line: 405", true, p2.equals(p1)); 
    assertEquals("From: Paasy line: 406", false, p1.equals(p3)); 
    assertEquals("From: Paasy line: 407", false, p3.equals(p2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKysymys422 */
  @Test
  public void testGetKysymys422() {    // Paasy: 422
    Paasy p = new Paasy(); 
    assertEquals("From: Paasy line: 424", "Otsikko", p.getKysymys(1)); 
    assertEquals("From: Paasy line: 425", false, p.getKysymys(1) == "otsikko"); 
    assertEquals("From: Paasy line: 426", "Puhelin numero", p.getKysymys(4)); 
    assertEquals("From: Paasy line: 427", null, p.getKysymys(10)); 
  } // Generated by ComTest END
}