package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.22 18:10:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PaasyTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi94 */
  @Test
  public void testRekisteroi94() {    // Paasy: 94
    Paasy gmail1 = new Paasy(); 
    Paasy gmail2 = new Paasy(); 
    assertEquals("From: Paasy line: 97", 0, gmail1.getTunnusNro()); 
    gmail1.rekisteroi(); 
    assertEquals("From: Paasy line: 99", 1, gmail1.getTunnusNro()); 
    assertEquals("From: Paasy line: 100", 0, gmail2.getTunnusNro()); 
    gmail2.rekisteroi(); 
    assertEquals("From: Paasy line: 102", 2, gmail2.getTunnusNro()); 
  } // Generated by ComTest END
}