package passreg.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.19 08:37:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PassregTest {



  // Generated by ComTest BEGIN
  /** testGetPaasytLkm95 */
  @Test
  public void testGetPaasytLkm95() {    // Passreg: 95
    Passreg pg = new Passreg(); 
    assertEquals("From: Passreg line: 97", 0, pg.getPaasytLkm()); 
    Paasy gmail1 = new Paasy(); 
    gmail1.rekisteroi(); 
    gmail1.taytaGmailTiedoilla(); 
    pg.lisaa(gmail1); 
    assertEquals("From: Passreg line: 104", 1, pg.getPaasytLkm()); 
    Paasy gmail2 = new Paasy(); 
    gmail2.rekisteroi(); 
    gmail2.taytaGmailTiedoilla(); 
    pg.lisaa(gmail2); 
    assertEquals("From: Passreg line: 111", 2, pg.getPaasytLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa137 */
  @Test
  public void testLisaa137() {    // Passreg: 137
    Passreg passreg = new Passreg(); 
    Paasy p1 = new Paasy(); 
    p1.taytaGmailTiedoilla(); 
    p1.rekisteroi(); 
    assertEquals("From: Passreg line: 142", 0, passreg.getPaasytLkm()); 
    passreg.lisaa(p1); 
    assertEquals("From: Passreg line: 144", 1, passreg.getPaasytLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa154 */
  @Test
  public void testLisaa154() {    // Passreg: 154
    Passreg passreg = new Passreg(); 
    Kategoria k1 = new Kategoria("some"); 
    k1.rekisteroi(); 
    Kategoria k2 = new Kategoria("opiskelu"); 
    k2.rekisteroi(); 
    Kategoria k3 = new Kategoria("työ"); 
    k3.rekisteroi(); 
    assertEquals("From: Passreg line: 162", 0, passreg.getKategoriatLkm()); 
    try {
    passreg.annaKategoria(0); 
    fail("Passreg: 163 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    passreg.lisaa(k1); 
    assertEquals("From: Passreg line: 165", 1, passreg.getKategoriatLkm()); 
    assertEquals("From: Passreg line: 166", "some", passreg.annaKategoria(0).getNimi()); 
    passreg.lisaa(k2); 
    assertEquals("From: Passreg line: 168", 2, passreg.getKategoriatLkm()); 
    assertEquals("From: Passreg line: 169", "opiskelu", passreg.annaKategoria(1).getNimi()); 
    passreg.lisaa(k3); 
    assertEquals("From: Passreg line: 171", 3, passreg.getKategoriatLkm()); 
    assertEquals("From: Passreg line: 172", "työ", passreg.annaKategoria(2).getNimi()); 
    try {
    passreg.annaKategoria(3); 
    fail("Passreg: 173 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta224 */
  @Test
  public void testLueTiedostosta224() {    // Passreg: 224
    Passreg regis = new Passreg(); 
    Kategoria k1 = new Kategoria("opiskelu"); k1.rekisteroi(); 
    Kategoria k2 = new Kategoria("viihde"); k2.rekisteroi(); 
    Paasy p1 = new Paasy(k1.getTunnusNro()); p1.taytaGmailTiedoilla(); 
    Paasy p2 = new Paasy(k2.getTunnusNro()); p2.taytaGmailTiedoilla(); 
    Paasy p3 = new Paasy(k2.getTunnusNro()); p3.taytaGmailTiedoilla(); 
    Paasy p4 = new Paasy(k1.getTunnusNro()); p4.taytaGmailTiedoilla(); 
    Paasy p5 = new Paasy(k2.getTunnusNro()); p5.taytaGmailTiedoilla(); 
    String hakemisto = "testi"; 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    regis.lueTiedostosta(hakemisto); 
    regis.lisaa(p1); 
    regis.lisaa(p2); 
    regis.lisaa(p3); 
    regis.lisaa(k1); 
    regis.lisaa(p4); 
    regis.lisaa(k2); 
    regis.lisaa(p5); 
    regis.tallenna(); 
    List<Paasy> pst = regis.getPaasyt(k1.getTunnusNro()); 
    Iterator<Paasy> it = pst.iterator(); 
    assertEquals("From: Passreg line: 249", p1, it.next()); 
    assertEquals("From: Passreg line: 250", p4, it.next()); 
    assertEquals("From: Passreg line: 251", false, it.hasNext()); 
    List<Paasy> loytyneet = regis.getPaasyt(k2.getTunnusNro()); 
    Iterator<Paasy> ih = loytyneet.iterator(); 
    assertEquals("From: Passreg line: 254", true, ih.hasNext()); 
    assertEquals("From: Passreg line: 255", p2, ih.next()); 
    assertEquals("From: Passreg line: 256", p3, ih.next()); 
    assertEquals("From: Passreg line: 257", true, ih.hasNext()); 
    assertEquals("From: Passreg line: 258", p5, ih.next()); 
    try {
    ih.next(); 
    fail("Passreg: 259 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPaasyt292 */
  @Test
  public void testGetPaasyt292() {    // Passreg: 292
    Passreg pss = new Passreg(); 
    Kategoria k = new Kategoria(); 
    int n = k.getTunnusNro(); 
    pss.lisaa(k); 
    Paasy p1 = new Paasy(n); p1.taytaGmailTiedoilla(); 
    Paasy p2 = new Paasy(n); p1.taytaGmailTiedoilla(); 
    Paasy p3 = new Paasy(n+1); p3.taytaGmailTiedoilla(); 
    pss.lisaa(p1); pss.lisaa(p2); pss.lisaa(p3); 
    List<Paasy> pst = pss.getPaasyt(n); 
    Iterator<Paasy> i = pst.iterator(); 
    assertEquals("From: Passreg line: 304", p1, i.next()); 
    assertEquals("From: Passreg line: 305", p2, i.next()); 
    assertEquals("From: Passreg line: 306", false, i.hasNext()); 
    try {
    i.next(); 
    fail("Passreg: 307 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}