package passreg.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import passreg.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.26 11:19:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PassregTest {



  // Generated by ComTest BEGIN
  /** testGetPaasytLkm74 */
  @Test
  public void testGetPaasytLkm74() {    // Passreg: 74
    Passreg pg = new Passreg(); 
    assertEquals("From: Passreg line: 76", 0, pg.getPaasytLkm()); 
    Paasy gmail1 = new Paasy(); 
    gmail1.rekisteroi(); 
    gmail1.taytaGmailTiedoilla(); 
    pg.lisaa(gmail1); 
    assertEquals("From: Passreg line: 83", 1, pg.getPaasytLkm()); 
    Paasy gmail2 = new Paasy(); 
    gmail2.rekisteroi(); 
    gmail2.taytaGmailTiedoilla(); 
    pg.lisaa(gmail2); 
    assertEquals("From: Passreg line: 90", 2, pg.getPaasytLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKategoriatLkm100 */
  @Test
  public void testGetKategoriatLkm100() {    // Passreg: 100
    Passreg passreg = new Passreg(); 
    Kategoria kg1 = new Kategoria(); 
    kg1.rekisteroi(); 
    kg1.taytaSomeenTiedoilla(); 
    Kategoria kg2 = new Kategoria(); 
    kg2.rekisteroi(); 
    kg2.taytaSomeenTiedoilla(); 
    Kategoria kg3 = new Kategoria(); 
    kg3.rekisteroi(); 
    kg2.taytaSomeenTiedoilla(); 
    assertEquals("From: Passreg line: 115", 0, passreg.getKategoriatLkm()); 
    passreg.lisaa(kg1); 
    assertEquals("From: Passreg line: 117", 1, passreg.getKategoriatLkm()); 
    passreg.lisaa(kg2); 
    assertEquals("From: Passreg line: 119", 2, passreg.getKategoriatLkm()); 
    passreg.lisaa(kg3); 
    assertEquals("From: Passreg line: 121", 3, passreg.getKategoriatLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa157 */
  @Test
  public void testLisaa157() {    // Passreg: 157
    Passreg passreg = new Passreg(); 
    Kategoria kg1 = new Kategoria(); 
    kg1.rekisteroi(); 
    kg1.taytaSomeenTiedoilla(); 
    Kategoria kg2 = new Kategoria(); 
    kg2.rekisteroi(); 
    kg2.taytaSomeenTiedoilla(); 
    Kategoria kg3 = new Kategoria(); 
    kg3.rekisteroi(); 
    kg2.taytaSomeenTiedoilla(); 
    assertEquals("From: Passreg line: 172", 0, passreg.getKategoriatLkm()); 
    passreg.lisaa(kg1); 
    assertEquals("From: Passreg line: 174", "some", passreg.annaKategoria(0).getNimi()); 
    assertEquals("From: Passreg line: 175", 1, passreg.getKategoriatLkm()); 
    passreg.lisaa(kg2); 
    assertEquals("From: Passreg line: 177", 2, passreg.getKategoriatLkm()); 
    passreg.lisaa(kg3); 
    assertEquals("From: Passreg line: 179", 3, passreg.getKategoriatLkm()); 
  } // Generated by ComTest END
}