package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.Merkkijonot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.25 17:09:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkijonotTest {



  // Generated by ComTest BEGIN
  /** testYhdista91 */
  @Test
  public void testYhdista91() {    // Merkkijonot: 91
    char[] PIENET_KIRJAIMET  = "abcdefghijklmnopqrstuvwxyz".toCharArray(); 
    char[] NUMEROT           = "0123456789".toCharArray(); 
    assertEquals("From: Merkkijonot line: 94", true, yhdista(PIENET_KIRJAIMET, NUMEROT).equals("abcdefghijklmnopqrstuvwxyz0123456789".toCharArray())); ; 
  } // Generated by ComTest END
}