package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.MerkkijononGenerointi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.22 17:42:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkijononGenerointiTest {



  // Generated by ComTest BEGIN
  /** testYhdista105 */
  @Test
  public void testYhdista105() {    // MerkkijononGenerointi: 105
    char[] PIENET_KIRJAIMET  = "abcdefghijklmnopqrstuvwxyz".toCharArray(); 
    char[] NUMEROT           = "0123456789".toCharArray(); 
    assertEquals("From: MerkkijononGenerointi line: 108", true, yhdista(PIENET_KIRJAIMET, NUMEROT).equals("abcdefghijklmnopqrstuvwxyz0123456789".toCharArray())); ; 
  } // Generated by ComTest END
}