package kanta.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.Merkkijonot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.11 12:28:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkijonotTest {



  // Generated by ComTest BEGIN
  /** testGenerateMerkkiJono29 */
  @Test
  public void testGenerateMerkkiJono29() {    // Merkkijonot: 29
    char[] merkit = new char[] { 'a', 'b', 'c'} ; 
    String g = generateMerkkiJono(merkit, 2, 10); 
    assertEquals("From: Merkkijonot line: 32", true, (g.length() >= 2 && g.length() <= 10)); 
    assertEquals("From: Merkkijonot line: 33", -1, g.indexOf("ä")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGeneroiTunnus61 */
  @Test
  public void testGeneroiTunnus61() {    // Merkkijonot: 61
    String tun = generoiTunnus(); 
    assertEquals("From: Merkkijonot line: 63", true, tun.length() <= 10); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGeneroiSalasana77 */
  @Test
  public void testGeneroiSalasana77() {    // Merkkijonot: 77
    String sala = generoiSalasana(10, new boolean[] {false, false, true}); 
    assertEquals("From: Merkkijonot line: 79", 10, sala.length()); 
    assertEquals("From: Merkkijonot line: 80", false, sala.contains("[0-9]")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGeneroiPuhNro100 */
  @Test
  public void testGeneroiPuhNro100() {    // Merkkijonot: 100
    String puh = generoiPuhNro(); 
    puh.startsWith("0"); 
    assertEquals("From: Merkkijonot line: 103", false, puh.contains("[a-zA-Z]")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testYhdista116 */
  @Test
  public void testYhdista116() {    // Merkkijonot: 116
    char[] PIENET_KIRJAIMET  = "abcdefghijklmnopqrstuvwxyz".toCharArray(); 
    char[] NUMEROT           = "0123456789".toCharArray(); 
    char[] yhdistetty = yhdista(PIENET_KIRJAIMET, NUMEROT); 
    assertEquals("From: Merkkijonot line: 120", "[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]", Arrays.toString(yhdistetty)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGeneroiKNimi150 */
  @Test
  public void testGeneroiKNimi150() {    // Merkkijonot: 150
    String kNimi= generoiKNimi(); 
    assertEquals("From: Merkkijonot line: 152", true, (kNimi.length() < 11) && kNimi.length() >= 5); 
    assertEquals("From: Merkkijonot line: 153", false, kNimi.contains("[0-9A-Z]")); 
  } // Generated by ComTest END
}