package kanta.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.Merkkijonot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.04 18:30:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkijonotTest {



  // Generated by ComTest BEGIN
  /** testGenerateMerkkiJono44 */
  @Test
  public void testGenerateMerkkiJono44() {    // Merkkijonot: 44
    char[] merkit = new char[] { 'a', 'b', 'c'} ; 
    String g = generateMerkkiJono(merkit, 2, 10); 
    assertEquals("From: Merkkijonot line: 47", true, (g.length() >= 2 && g.length() <= 10)); 
    assertEquals("From: Merkkijonot line: 48", -1, g.indexOf("ä")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testYhdista140 */
  @Test
  public void testYhdista140() {    // Merkkijonot: 140
    char[] PIENET_KIRJAIMET  = "abcdefghijklmnopqrstuvwxyz".toCharArray(); 
    char[] NUMEROT           = "0123456789".toCharArray(); 
    char[] yhdistetty = yhdista(PIENET_KIRJAIMET, NUMEROT); 
    assertEquals("From: Merkkijonot line: 144", "[a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]", Arrays.toString(yhdistetty)); 
  } // Generated by ComTest END
}