package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.Tarkistukset.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.26 08:47:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TarkistuksetTest {



  // Generated by ComTest BEGIN
  /** testOnValidiEmail30 */
  @Test
  public void testOnValidiEmail30() {    // Tarkistukset: 30
    assertEquals("From: Tarkistukset line: 31", false, onValidiEmail("abc@gmail.com")); 
    assertEquals("From: Tarkistukset line: 32", true, onValidiEmail("abcdef@edu.hel.fi")); 
    assertEquals("From: Tarkistukset line: 33", false, onValidiEmail("@yahoo.")); 
    assertEquals("From: Tarkistukset line: 34", false, onValidiEmail("...@yahoo.com")); 
    assertEquals("From: Tarkistukset line: 35", true, onValidiEmail("kkk11kk@hotmail.com")); 
    assertEquals("From: Tarkistukset line: 36", false, onValidiEmail("matti.meikäläinen@gmail.com.")); 
    assertEquals("From: Tarkistukset line: 37", false, onValidiEmail("matti.meikäläinen@gmail.com")); 
    assertEquals("From: Tarkistukset line: 38", true, onValidiEmail("matti.meikalainen@gmail.com")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnValidiTunnus52 */
  @Test
  public void testOnValidiTunnus52() {    // Tarkistukset: 52
    assertEquals("From: Tarkistukset line: 53", true, onValidiTunnus("soturi123", 6, 30)); 
    assertEquals("From: Tarkistukset line: 54", false, onValidiTunnus("?!jdkds", 2, 10)); 
    assertEquals("From: Tarkistukset line: 55", false, onValidiTunnus("123UpQz", 10, 14)); 
    assertEquals("From: Tarkistukset line: 56", true, onValidiTunnus("MattiM" , 6, 12)); 
  } // Generated by ComTest END
}